/**
 * This file was automatically generated by json-schema-to-typescript. DO NOT
 * MODIFY IT BY HAND. Instead, modify the source JSONSchema file, and run
 * json-schema-to-typescript to regenerate this file.
 */

export interface DependencyGeneratorSchema {
  /** Project name */
  project: string;
  /** Chart Name of the Dependency */
  chartName?: string;
  /** Chart Version of the Dependency */
  chartVersion?: string;
  /** Repository of the Dependency */
  repository: string;
  /** Repository Name of the Dependency */
  repositoryName: string;
  /** Format the generated files */
  format?: boolean;
  [k: string]: unknown;
}
