/**
 * This file was automatically generated by json-schema-to-typescript. DO NOT
 * MODIFY IT BY HAND. Instead, modify the source JSONSchema file, and run
 * json-schema-to-typescript to regenerate this file.
 */

export interface PackageExecutorSchema {
  /** Folder where the chart is stored */
  chartFolder: string;
  /** Folder to store the packaged chart */
  outputFolder: string;
  /** Publish the chart to a repository */
  publish?: boolean;
  [k: string]: unknown;
}
