/**
 * This file was automatically generated by json-schema-to-typescript. DO NOT
 * MODIFY IT BY HAND. Instead, modify the source JSONSchema file, and run
 * json-schema-to-typescript to regenerate this file.
 */

export interface PackageExecutorSchema {
  /** Folder where the chart is stored */
  chartFolder: string;
  /** Folder to store the packaged chart */
  outputFolder: string;
  /** Push the chart to a remote registry */
  push?: boolean;
  /** Remote registry to publish the chart */
  remote?: string;
  [k: string]: unknown;
}
