/**
 * This file was automatically generated by json-schema-to-typescript. DO NOT
 * MODIFY IT BY HAND. Instead, modify the source JSONSchema file, and run
 * json-schema-to-typescript to regenerate this file.
 */

export interface ChartGeneratorSchema {
  /** Name of the chart */
  name: string;
  /** Name of the project to add the chart to */
  project: string;
  /** Folder to store the chart */
  chartFolder?: string;
  [k: string]: unknown;
}
