# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE || 'false' }}

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - uses: azure/setup-helm@v4.3.1
        with:
          version: '3.8.0'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}

      - run: npx nx format:check
      - run: npx nx affected -t test --verbose --parallel 3
      - run: npx nx affected -t lint --verbose --parallel 3
      - run: npx nx affected -t e2e --verbose --parallel 3
      - run: npx nx affected -t build --verbose --parallel 3
