# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Publish

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: Dry Run
        default: false
        required: false
      projects:
        type: string
        description: Projects to publish
        default: ''
        required: false

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Parse project name from git tag if not provided
        run: |
          if [ -z "${{ inputs.projects }}" ]; then
            export PROJECTS=$(echo ${{ github.ref }} | cut -d'@' -f1)
          else
            export PROJECTS=${{ inputs.projects }}
          fi
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Build packages
        run: npx nx run-many --target build --parallel 3 --configuration production --verbose

      - name: Publish packages
        run: |
          if [ ${{env.DRY_RUN}} == true ]; then
            npx nx release publish --dryRun --projects ${{env.PROJECTS}} --verbose
          else
            npx nx release publish --projects ${{env.PROJECTS}} --verbose
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          DRY_RUN: ${{ inputs.dryRun }}
          PROJECTS: ${{ env.PROJECTS }}
